#!/usr/bin/php
<?php
// First we need to include our auth script and some needed tools
require_once('/usr/share/php/opencloud/lib/rackspace.php');
require_once('./auth.php');

// Now we set some common variables
$compute = $RAX->Compute();
$server = $compute->Server();

//we need the user to define some info for us; How many servers 1-3 and a name.
printf("Would you like to build 1, 2, or 3 servers? \n");

$numservs = trim(fgets(STDIN));

$min = 1;
$max = 3;

//now we test it to see if it is a num and to make sure it is 1,2, or 3
while (filter_var($numservs, FILTER_VALIDATE_INT, array("options" => array("min_range"=>$min, "max_range"=>$max))) == FALSE) {
	echo "Error: Please enter 1, 2, or 3. \n";
	$numservs = trim(fgets(STDIN));
}

printf("What would you like your server name to be?  \n");

$servname = trim(fgets(STDIN));

while (ctype_alnum($servname) == FALSE) {
	echo "Error: Please use alpha numeric characters only! \n";
	$servname = trim(fgets(STDIN));
}




// Lets build our server/s, I am using static variables for flavor and image just to keep this easy
$count = 1;
while ($count <= $numservs) {

$name = "$servname$count";

$server->name = $name;
$server->flavor = $compute->flavor(2);
$server->image = $compute->image('bced783b-31d2-4637-b820-fa02522c518b');
$server->create();

// Now we need to grab some info that is populated during the create function

// here we need to assign variables for this iteration;

${"pass$count"} = $server->adminPass;
${"id$count"} = $server->id();

//some output for the user
printf("Building server $name now! \n");

$count++;

}

$count = 1;

while ($count <= $numservs) {
// We need to wait for the server to be active to grab the IP;
	do {
		sleep(30);
//the next line is going to pull the info fresh from the server object we created earlier (THIS IS IMPORTANT!!
		$id = "id$count";
		$server = $compute->Server($id);
		$status = $server->status();
		printf("Still building...\n");
	} while ($status == "BUILD");
	
//if the server is no longer in "BUILD" it should be ACTIVE, but we all know what happens when we assume...
	if ($status!="ACTIVE") {	
		echo sprintf(
			"ERROR Server state is %s!!",
			$status
		);
		$count++;
	}	
	else {
		$name = "$servname$count";
		$ip = $server->ip(4);
		echo sprintf(
			"Sever %s is complete! The root pass is %s, and the IP is %s",
			$name,
			$pass$count,
			$ip
		);
		$count++;
	}
}	
?>

