#!/usr/bin/php
<?php
// First we need to include our auth script and some needed tools
require_once('/usr/share/php/opencloud/lib/rackspace.php');
require_once('./auth.php');

// Now we set some common variables
$compute = $RAX->Compute();
$server = $compute->Server();
$name = 'AndersTestNew';

// Lets build our server, I am using static variables for flavor and image just to keep this easy
$server->name = $name;
$server->flavor = $compute->flavor(2);
$server->image = $compute->image('b01aa33e-2563-4ee9-9c29-071852cb872c');
$server->create();

// Now we need to grab some info that is populated during the create function
$pass = $server->adminPass;
$id = $server->id();

//some output for the user
printf("Building server now! \n");

// We need to wait for the server to be active to grab the IP;
do {
	sleep(30);
//the next line is going to pull the info fresh from the server object we created earlier (THIS IS IMPORTANT!!
	$server = $compute->Server($id);
	$status = $server->status();
	printf("Still building...\n");
} while ($status == "BUILD");

//if the server is no longer in "BUILD" it should be ACTIVE, but we all know what happens when we assume...

if ($status!="ACTIVE")
{
	echo sprintf(
		"ERROR Server state is %s!!",
		$status
	);
}
else {
	$ip = $server->ip(4);
	echo sprintf(
		"Sever %s is complete! The root pass is %s, and the IP is %s",
		$name,
		$pass,
		$ip
	);
}
?>

